const Vars = import.meta.env;

export const AppConfig = {
  APP: Vars.VITE_CLIENT_APP,
  PROJECTS: Vars.VITE_PROJECTS?.split(","),
  AUTH: {
    EXCHANGE_URI: Vars.VITE_PERMITRA_EXCHANGE_URI,
    REFRESH_URI: Vars.VITE_PERMITRA_REFRESH_URI,
    PERMITRA_URI: Vars.VITE_PERMITRA_URI,
    CALLBACK: Vars.VITE_AUTH_CALLBACK,
    GET_USER_INFO: Vars.VITE_PERMITRA_GET_USER_INFO,
    LOGIN_PAGE: Vars.VITE_LOGIN_ENDPOINT
  },
  SERVERS: {
    PERMITRA: Vars.VITE_PERMITRA_SERVER,
    PERMITRA_UI: Vars.VITE_PERMITRA_FRONTEND_SERVER,
    LOG_STREAMR: Vars.VITE_LOG_STREAMR_SERVER,
    CONTROL_DECK: Vars.VITE_CONTROL_DECK_FRONTEND_SERVER
  }
};
